---
- name: Add PPA
  apt_repository: repo='ppa:webupd8team/java'
  when: ansible_distribution != "Linuxmint"

- name: Add PPA (Linuxmint Workaround)
  shell: add-apt-repository -y ppa:webupd8team/java
  become: true
  when: ansible_distribution == "Linuxmint"
  
- name: Bypass Oracle Popup Window
  shell: "echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections && echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections"
  sudo: yes
  
- name: Install
  apt:  pkg={{ item }}
        state=installed
        update_cache=yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default

- name: Set JAVA_HOME
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "{{ item.regex }}"
    line: "{{ item.line }}"
    create: yes
  sudo: yes
  with_items:
    - { regex: "^JAVA_HOME=*", line: "JAVA_HOME=/usr/lib/jvm/java-8-oracle/"}
    - { regex: "^export JAVA_HOME*", line: "export JAVA_HOME"}
